name: accessing env
on: workflow_dispatch
env:
  APP_ENV: "test"
jobs:
  checkEnv:
    env:
      APP_ENV: "dev"
    runs-on: ubuntu-latest
    steps:
      - name: accessing Env variable
        run: echo "Env is $APP_ENV"
        env:
          APP_ENV: "dev"
