name: Build & Deploy
on:
  workflow_dispatch
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    # running the build only when pull_request is done against the main-branch. otherwise it will not run.
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Build app
        run: echo "building app"

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Deploy app
        run: echo "deploying application"
