# requirement we want to run job build on PR and delpoy when we are doing push to main branch.
name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name = 'pull_request'
    steps:
      - name: building app
        run: echo "building app"

  delpoy:
    runs-on: ubuntu-latest
    if: github.ref_name = 'main'
    steps:
      - name: deploying app
        run: echo "deploying application"
