name: accepting inputs in acitons
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "type the environment to deploy"
        required: true
        default: "dev"
jobs:
  input-access:
    runs-on: ubuntu-latest
    steps:
      - name: using inputs in GHA
        run: echo "Environment ${{ inputs.environment }}"
