name: accepting inputs in acitons
on:
  workflow_dispatch:
    inputs:
      artifact_tag:
        description: "version of deployment"
        required: true
      environment:
        description: "type the environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - prod
          - dev
          - test
jobs:
  input-access:
    runs-on: ubuntu-latest
    steps:
      - name: using inputs in GHA
        run: echo "Environment ${{ inputs.environment }}, tag ${{ inputs.artifact_tag }} "
