name: multiple jobs in a workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: building step
        run: echo "Building"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test step
        run: echo "Testing"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy step
        run: echo "Deploying"
