name: sharing output b/w jobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.step1.outputs.service}}
    steps:
      - name: Some steps work
        id: step1
        run: echo "service=0.1.1" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploying the applicaiton.
        run: echo "${{needs.build.outputs.version}}"
