name: sharing output b/w steps
on: workflow_dispatch
jobs:
  output-sharing:
    runs-on: ubuntu-latest
    steps:
      - name: Some steps work
        id: step1
        run: echo "service=0.1.1" >> $GITHUB_OUTPUT
      - name: step 2
        run: echo "The service version is ${{ steps.step1.outputs.service }}"
